version: '3.1'
services:
  app:
    container_name: application
    image: eshop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2cool4u
    container_name: "postgres"
    ports:
      - "6666:5432"
    labels:
      description: "Postgresql Database"
      service: "postgresql"