version: '3.1'
services:
  app:
    container_name: application
    image: spring-boot-docker.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    command: "-i"
    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2cool4u
    container_name: "postgres"
    volumes:
      - ./sql_script/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./sql_script/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - "6666:5432"
    labels:
      description: "Postgresql Database"
      service: "postgresql"